# Site settings
title: fearythanyarat
email: ""
description: "Thanyarat Charoenpornkittada"
url: "https://fearythanyarat.github.io"
baseurl: ""
facebook_username: "fearythanyarat.char"
# twitter_username: ""
instagram_username: "fearythanyarat"
# github_username:  ""
# deviantart_username: ""
# flickr_username: ""
# discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   zhouqian
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template
  statistics: "baidu_statistics.html"

  # Set the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
  # set this field to false to turn commenting off globally
  # Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
  comments: "disqus_comments.html"
  direct_link_base: "http://ctfile.zhouqian.tech/down/217373/fearythanyarat"


# Internal nav
nav:
  - GALLERY: "/gallery/"  
  - JOURNAL: "/journal/"
  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:       ./_site
port:              4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
plugins:
 - jekyll-paginate
 - jekyll-admin
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
